# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://work.myusc.net/
title: USC Computer Services
email: webmaster@myusc.net
author: Dayron Acosta
description: USC Computer Services
copyright: 'Copyright &copy; 2025 USC Computer Services, LLC. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/company/usc-computer-services/
